Calendar/Models/PartialModels/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Calendar.Models
{
    [MetadataType(typeof(UserMetadata))]
    public partial class User
    {
        public User(string login, string password, double timeZone)
        {
            Login = login;
            Password = password;
            TimeZone = timeZone;
        }

    }
}

Calendar/Models/User.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Calendars = new HashSet<Calendar>();
            this.SharedCalendars = new HashSet<SharedCalendar>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public double TimeZone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calendar> Calendars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SharedCalendar> SharedCalendars { get; set; }
    }
}

Calendar/Controllers/CalendarController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Calendar.Models;
using Calendar.ViewModels;

namespace Calendar.Controllers
{
    public class CalendarController : Controller
    {

        /// <summary>
        /// Return view where user may create new calendar.
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login", "User");
            }

            return View();
        }

        /// <summary>
        /// Adds new calendar to database. When validation fails sends back to Create page where user may fix errors.
        /// </summary>
        /// <param name="calendar"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(Models.Calendar calendar)
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login", "User");
            }

            CalendarEntityContainer db = new CalendarEntityContainer();
            if (db.Calendars.Any(c => c.Name.Equals(calendar.Name, StringComparison.InvariantCultureIgnoreCase)))
            {
                ModelState.AddModelError("", "Calendar with this name already exists");
            }

            if (!ModelState.IsValid)
            {
                return View(calendar);
            }

            User user = (User)Session["LoggedUser"];

            calendar.OwnerId = user.Id;

            db.Calendars.Add(calendar);
            db.SaveChanges();
            return RedirectToAction("Show", new { id = calendar.Id, selectedDate = DateTime.Now });
        }

        /// <summary>
        /// Show selected calendar. Parameter SelectedDate is used to define on which month and year calendar should be shown.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="selectedDate"></param>
        /// <returns></returns>
        public ActionResult Show(int id, DateTime selectedDate)
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login", "User");
            }

            CalendarEntityContainer db = new CalendarEntityContainer();

            Models.Calendar calendar = db.Calendars.FirstOrDefault(c => c.Id == id);

            if (calendar == null)
            {
                return new HttpNotFoundResult();
            }

            AccessLevel accessLevel = calendar.GetUserAccessLevel(((User)Session["LoggedUser"]).Id);

            if (accessLevel == AccessLevel.None)
            {
                return new HttpUnauthorizedResult();
            }

            foreach (Event item in calendar.Events)
            {
                item.ChangeToLocalTime(((User)Session["LoggedUser"]).TimeZone);
            }

            CalendarViewModel calendarViewModel = new CalendarViewModel(calendar,
                Models.Calendar.GetFirstDayDate(selectedDate), accessLevel);

            if (accessLevel == AccessLevel.Owner)
            {
                int userId = ((User)Session["LoggedUser"]).Id;
                IEnumerable<User> usersToShare = db.Users.Where(u => u.Id != userId && !db.SharedCalendars.Any(s => s.CalendarId == calendar.Id && s.UserId == u.Id));
                calendarViewModel.UsersToShare = usersToShare;

                IEnumerable<User> usersShared = db.Users.Where(u => u.Id != userId && db.SharedCalendars.Any(s => s.CalendarId == calendar.Id && s.UserId == u.Id));
                calendarViewModel.UsersShared = usersShared;
            }

            return View(calendarViewModel);
        }

        /// <summary>
        /// Gives selected access level to user. Redirects to Show page.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="userId"></param>
        /// <param name="access"></param>
        /// <param name="selectedDate"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Share(int id, int userId, AccessLevel access, DateTime selectedDate)
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login", "User");
            }

            CalendarEntityContainer db = new CalendarEntityContainer();
            User user = db.Users.FirstOrDefault(u => u.Id == userId);

            if (user == null)
            {
                return new HttpNotFoundResult();
            }

            Models.Calendar calendar = db.Calendars.FirstOrDefault(c => c.Id == id);

            if (calendar == null)
            {
                return new HttpNotFoundResult();
            }

            AccessLevel accessLevel = calendar.GetUserAccessLevel(((User)Session["LoggedUser"]).Id);

            if (accessLevel != AccessLevel.Owner)
            {
                return new HttpUnauthorizedResult();
            }

            db.SharedCalendars.Add(new SharedCalendar(id, userId, access));
            db.SaveChanges();
            TempData.Add("SharedCalendar", user.Login);
            return RedirectToAction("Show", new { id = id, selectedDate = selectedDate });
        }

        /// <summary>
        /// Remove access level to calendar from selected user. Redirects to Show page.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="userId"></param>
        /// <param name="selectedDate"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult RemoveAccess(int id, int userId, DateTime selectedDate)
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login", "User");
            }

            CalendarEntityContainer db = new CalendarEntityContainer();
            User user = db.Users.FirstOrDefault(u => u.Id == userId);

            if (user == null)
            {
                return new HttpNotFoundResult();
            }

            Models.Calendar calendar = db.Calendars.FirstOrDefault(c => c.Id == id);

            if (calendar == null)
            {
                return new HttpNotFoundResult();
            }

            AccessLevel accessLevel = calendar.GetUserAccessLevel(((User)Session["LoggedUser"]).Id);

            if (accessLevel != AccessLevel.Owner)
            {
                return new HttpUnauthorizedResult();
            }

            SharedCalendar scToDelete =
                db.SharedCalendars.FirstOrDefault(s => s.CalendarId == id && s.UserId == userId);
            db.SharedCalendars.Remove(scToDelete);
            db.SaveChanges();
            TempData.Add("RemovedAccess", user.Login);
            return RedirectToAction("Show", new { id = id, selectedDate = selectedDate });
        }
    }
}

Calendar/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Calendar.Models;
using Calendar.ViewModels;

namespace Calendar.Controllers
{
    public class UserController : Controller
    {
        /// <summary>
        /// Shows login page.
        /// </summary>
        /// <returns></returns>
        public ActionResult Login()
        {
            if (Session["LoggedUser"] != null)
            {
                return RedirectToAction("MyCalendars");
            }
            return View();
        }

        /// <summary>
        /// Tries to log in selected user.
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Login(User user)
        {
            if (Session["LoggedUser"] != null)
            {
                return RedirectToAction("MyCalendars");
            }

            CalendarEntityContainer db = new CalendarEntityContainer();

            User loggedUser = db.Users.FirstOrDefault(u =>
                        u.Login.Equals(user.Login, StringComparison.InvariantCulture) &&
                        u.Password.Equals(user.Password, StringComparison.InvariantCulture));

            if (loggedUser == null)
            {
                ModelState.AddModelError("", "There is no such user or password is incorrect");
            }

            if (ModelState.IsValid)
            {
                Session.Add("LoggedUser", loggedUser);
                return RedirectToAction("MyCalendars");
            }

            return View(user);
        }

        /// <summary>
        /// Show register page.
        /// </summary>
        /// <returns></returns>
        public ActionResult Register()
        {
            if (Session["LoggedUser"] != null)
            {
                return RedirectToAction("MyCalendars");
            }

            return View();
        }

        /// <summary>
        /// Tries to register user in database.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Register(RegistrationUser model)
        {
            if (Session["LoggedUser"] != null)
            {
                return RedirectToAction("MyCalendars");
            }

            CalendarEntityContainer db = new CalendarEntityContainer();

            if (model.TimeZone > 99)
            {
                ModelState.AddModelError("", "You must choose your time zone");
            }

            if (db.Users.Count(m => m.Login == model.Login) > 0)
                ModelState.AddModelError("", "User with the same login name already exists");

            if (ModelState.IsValid)
            {
                TempData.Add("RegisteredUser", model.Login);

                db.Users.Add(new User(model.Login, model.Password, model.TimeZone));
                db.SaveChanges();
                return RedirectToAction("Login");
            }
            return View(model);
        }

        /// <summary>
        /// Show My Calendars page where user may choose one of his calendar.
        /// </summary>
        /// <returns></returns>
        public ActionResult MyCalendars()
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login");
            }
            User user = (User)Session["LoggedUser"];
            CalendarEntityContainer db = new CalendarEntityContainer();
            IEnumerable<Models.Calendar> calendars = db.Calendars.Where(c => c.OwnerId == user.Id);
            IEnumerable<Models.Calendar> sharedCalendars = db.Calendars.Where(c => db.SharedCalendars.Any(w => w.UserId == user.Id && c.Id == w.CalendarId));

            return View(new AvailableCalendarsViewModel(calendars, sharedCalendars));
        }

        /// <summary>
        /// Log user out from application
        /// </summary>
        /// <returns></returns>
        public ActionResult Logout()
        {
            Session.Remove("LoggedUser");
            return RedirectToAction("Login");
        }
    }
}

Calendar/Views/User/Login.cshtml
@using System.Web.UI.WebControls
@model global::Calendar.Models.User

@{
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
    ViewBag.Title = "Login";
}

@if (TempData["RegisteredUser"] != null)
{
        <div class="alert alert-success" role="alert">Successfully registered user @TempData["RegisteredUser"]</div>
}
@using (Html.BeginForm("Login", "User", null, FormMethod.Post, new { style = "max-width:330px;margin:0 auto" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <h2>Please sign in</h2>
    <div>
        @Html.TextBoxFor(model => model.Login, new { @class = "form-control", placeholder = "Login" })
        @Html.ValidationMessageFor(model => model.Login)
    </div>
    <div>
        @Html.TextBoxFor(model => model.Password, new { @class = "form-control", placeholder = "Password", type = "Password" })
        @Html.ValidationMessageFor(model => model.Password)
    </div>

    <p>
        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Sign In" />
    </p>
}

Calendar/Views/User/MyCalendars.cshtml
@model Calendar.ViewModels.AvailableCalendarsViewModel
@{
    ViewBag.Title = "My calendars";
}

<h2>Choose available calendar</h2>

<table>
    <tr>
        <td>
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                    Choose owned calendar
            <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    @foreach (Calendar.Models.Calendar item in Model.MyCalendars)
                    {
                        <li>@Html.ActionLink(item.Name, "Show", "Calendar", new { id = item.Id, selectedDate = DateTime.Now }, null)</li>
                    }
                </ul>
            </div>
        </td>
        <td>
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                    Choose shared calenadar
                <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    @foreach (Calendar.Models.Calendar item in Model.SharedCalendars)
                    {
                        <li>@Html.ActionLink(item.Name, "Show", "Calendar", new { id = item.Id, selectedDate = DateTime.Now }, null)</li>
                    }
                </ul>
            </div>
        </td>
    </tr>
</table>
<h2>Create new calendar</h2>

@using (Html.BeginForm("Create", "Calendar", null, FormMethod.Get))
{
    <p>
        <input class="btn btn-primary" type="submit" value="Create new calendar" />
    </p>
}

Calendar/Views/User/Register.cshtml
@model Calendar.ViewModels.RegistrationUser
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

@using (Html.BeginForm("Register", "User", FormMethod.Post, new { style = "max-width:330px;margin:0 auto" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
        
    <h2>Please sign up</h2>
    <div>
        @Html.TextBoxFor(model => model.Login, new { @class = "form-control", placeholder = "Login", autocomplete = false })
        @Html.ValidationMessageFor(model => model.Login)
    </div>

    <div>
        @Html.TextBoxFor(model => model.Password, new { @class = "form-control", placeholder = "Password", type = "Password", autocomplete = false })
        @Html.ValidationMessageFor(model => model.Password)
    </div>

    <div>
        @Html.TextBoxFor(model => model.RepeatPassword, new { @class = "form-control", placeholder = "Confirm password", type = "Password", autocomplete = false })
        @Html.ValidationMessageFor(model => model.RepeatPassword)
    </div>
    
    <div>
        <select class="form-control" name="TimeZone">
            <option value="-12">(GMT-12:00) International Date Line West</option>
            <option value="-11">(GMT-11:00) Midway Island, Samoa</option>
            <option value="-10">(GMT-10:00) Hawaii</option>
            <option value="-9">(GMT-09:00) Alaska</option>
            <option value="-8">(GMT-08:00) Pacific Time (US & Canada)</option>
            <option value="-8">(GMT-08:00) Tijuana, Baja California</option>
            <option value="-7">(GMT-07:00) Arizona</option>
            <option value="-7">(GMT-07:00) Chihuahua, La Paz, Mazatlan</option>
            <option value="-7">(GMT-07:00) Mountain Time (US & Canada)</option>
            <option value="-6">(GMT-06:00) Central America</option>
            <option value="-6">(GMT-06:00) Central Time (US & Canada)</option>
            <option value="-6">(GMT-06:00) Guadalajara, Mexico City, Monterrey</option>
            <option value="-6">(GMT-06:00) Saskatchewan</option>
            <option value="-5">(GMT-05:00) Bogota, Lima, Quito, Rio Branco</option>
            <option value="-5">(GMT-05:00) Eastern Time (US & Canada)</option>
            <option value="-5">(GMT-05:00) Indiana (East)</option>
            <option value="-4">(GMT-04:00) Atlantic Time (Canada)</option>
            <option value="-4">(GMT-04:00) Caracas, La Paz</option>
            <option value="-4">(GMT-04:00) Manaus</option>
            <option value="-4">(GMT-04:00) Santiago</option>
            <option value="-3,5">(GMT-03:30) Newfoundland</option>
            <option value="-3">(GMT-03:00) Brasilia</option>
            <option value="-3">(GMT-03:00) Buenos Aires, Georgetown</option>
            <option value="-3">(GMT-03:00) Greenland</option>
            <option value="-3">(GMT-03:00) Montevideo</option>
            <option value="-2">(GMT-02:00) Mid-Atlantic</option>
            <option value="-1">(GMT-01:00) Cape Verde Is.</option>
            <option value="-1">(GMT-01:00) Azores</option>
            <option value="0">(GMT+00:00) Casablanca, Monrovia, Reykjavik</option>
            <option value="100" selected>Select your time zone</option>
            <option value="0">(GMT+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London</option>
            <option value="1">(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna</option>
            <option value="1">(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague</option>
            <option value="1">(GMT+01:00) Brussels, Copenhagen, Madrid, Paris</option>
            <option value="1">(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb</option>
            <option value="1">(GMT+01:00) West Central Africa</option>
            <option value="2">(GMT+02:00) Amman</option>
            <option value="2">(GMT+02:00) Athens, Bucharest, Istanbul</option>
            <option value="2">(GMT+02:00) Beirut</option>
            <option value="2">(GMT+02:00) Cairo</option>
            <option value="2">(GMT+02:00) Harare, Pretoria</option>
            <option value="2">(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius</option>
            <option value="2">(GMT+02:00) Jerusalem</option>
            <option value="2">(GMT+02:00) Minsk</option>
            <option value="2">(GMT+02:00) Windhoek</option>
            <option value="3">(GMT+03:00) Kuwait, Riyadh, Baghdad</option>
            <option value="3">(GMT+03:00) Moscow, St. Petersburg, Volgograd</option>
            <option value="3">(GMT+03:00) Nairobi</option>
            <option value="3">(GMT+03:00) Tbilisi</option>
            <option value="3,5">(GMT+03:30) Tehran</option>
            <option value="4">(GMT+04:00) Abu Dhabi, Muscat</option>
            <option value="4">(GMT+04:00) Baku</option>
            <option value="4">(GMT+04:00) Yerevan</option>
            <option value="4,5">(GMT+04:30) Kabul</option>
            <option value="5">(GMT+05:00) Yekaterinburg</option>
            <option value="5">(GMT+05:00) Islamabad, Karachi, Tashkent</option>
            <option value="5,5">(GMT+05:30) Sri Jayawardenapura</option>
            <option value="5,5">(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi</option>
            <option value="5,75">(GMT+05:45) Kathmandu</option>
            <option value="6">(GMT+06:00) Almaty, Novosibirsk</option>
            <option value="6">(GMT+06:00) Astana, Dhaka</option>
            <option value="6,5">(GMT+06:30) Yangon (Rangoon)</option>
            <option value="7">(GMT+07:00) Bangkok, Hanoi, Jakarta</option>
            <option value="7">(GMT+07:00) Krasnoyarsk</option>
            <option value="8">(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi</option>
            <option value="8">(GMT+08:00) Kuala Lumpur, Singapore</option>
            <option value="8">(GMT+08:00) Irkutsk, Ulaan Bataar</option>
            <option value="8">(GMT+08:00) Perth</option>
            <option value="8">(GMT+08:00) Taipei</option>
            <option value="9">(GMT+09:00) Osaka, Sapporo, Tokyo</option>
            <option value="9">(GMT+09:00) Seoul</option>
            <option value="9">(GMT+09:00) Yakutsk</option>
            <option value="9,5">(GMT+09:30) Adelaide</option>
            <option value="9,5">(GMT+09:30) Darwin</option>
            <option value="10">(GMT+10:00) Brisbane</option>
            <option value="10">(GMT+10:00) Canberra, Melbourne, Sydney</option>
            <option value="10">(GMT+10:00) Hobart</option>
            <option value="10">(GMT+10:00) Guam, Port Moresby</option>
            <option value="10">(GMT+10:00) Vladivostok</option>
            <option value="11">(GMT+11:00) Magadan, Solomon Is., New Caledonia</option>
            <option value="12">(GMT+12:00) Auckland, Wellington</option>
            <option value="12">(GMT+12:00) Fiji, Kamchatka, Marshall Is.</option>
            <option value="13">(GMT+13:00) Nuku'alofa</option>
        </select>
        @Html.ValidationMessageFor(model => model.TimeZone)
    </div>

    <p>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
    </p>
}