Calendar/Models/Event.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool AllDay { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int CalendarId { get; set; }
    
        public virtual Calendar Calendar { get; set; }
    }
}

Calendar/Models/PartialModels/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Calendar.Models
{
    [MetadataType(typeof(EventMetadata))]
    public partial class Event
    {
        public Event(string title, string description)
        {
            Title = title;
            Description = description;
        }

        public Event()
        {
            EndTime = DateTime.Now;
        }

        public Event(DateTime startTime)
        {
            StartTime = startTime;
            EndTime = startTime;
        }

        /// <summary>
        /// Convert time to UTC time.
        /// </summary>
        /// <param name="addTime"></param>
        public void ChangeTimesToUTC(double addTime)
        {
            if ((addTime % 1) == 0)
            {
                StartTime = StartTime.AddHours((int)-addTime);
                EndTime = EndTime.AddHours((int)-addTime);
            }
            else
            {
                StartTime = StartTime.AddHours((int)-addTime);
                EndTime = EndTime.AddHours((int)-addTime);

                StartTime = StartTime.AddMinutes(-30);
                EndTime = EndTime.AddMinutes(-30);
            }
        }


        /// <summary>
        /// Convert time to selected by user time zone
        /// </summary>
        /// <param name="addTime"></param>
        public void ChangeToLocalTime(double addTime)
        {
            if ((addTime % 1) == 0)
            {
                StartTime = StartTime.AddHours((int)addTime);
                EndTime = EndTime.AddHours((int)addTime);
            }
            else
            {
                StartTime = StartTime.AddHours((int)addTime);
                EndTime = EndTime.AddHours((int)addTime);

                StartTime = StartTime.AddMinutes(30);
                EndTime = EndTime.AddMinutes(30);
            }
        }
    }
}

Calendar/Controllers/EventController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Calendar.Models;
using Calendar.ViewModels;

namespace Calendar.Controllers
{
    public class EventController : Controller
    {
        /// <summary>
        /// Show details page of selected event.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login", "User");
            }

            CalendarEntityContainer db = new CalendarEntityContainer();
            Event calendarEvent = db.Events.FirstOrDefault(e => e.Id == id);
            if (calendarEvent == null)
            {
                return new HttpNotFoundResult();
            }

            calendarEvent.ChangeToLocalTime(((User)Session["LoggedUser"]).TimeZone);

            return View(new EventDetailsViewModel(calendarEvent, calendarEvent.Calendar.GetUserAccessLevel(((User)Session["LoggedUser"]).Id)));
        }

        /// <summary>
        /// Show page where user may create new event.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="startDate"></param>
        /// <returns></returns>
        public ActionResult Create(int id, DateTime startDate)
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login", "User");
            }

            Event calendarEvent = new Event(startDate) { CalendarId = id };

            return View(calendarEvent);
        }

        /// <summary>
        /// Adds new event to database. When validation fails redirects user to Create page to fix errors.
        /// </summary>
        /// <param name="calendarEvent"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(Event calendarEvent)
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login", "User");
            }


            if (calendarEvent.AllDay)
            {
                calendarEvent.EndTime = calendarEvent.StartTime.AddDays(1);
            }

            if (calendarEvent.StartTime > calendarEvent.EndTime)
            {
                ModelState.AddModelError("", "Event end time cannot be before event start time.");
            }

            if (ModelState.IsValid)
            {
                CalendarEntityContainer db = new CalendarEntityContainer();

                Models.Calendar calendar = db.Calendars.FirstOrDefault(c => c.Id == calendarEvent.CalendarId);

                if (calendar == null)
                {
                    return new HttpNotFoundResult();
                }

                AccessLevel accessLevel = calendar.GetUserAccessLevel(((User)Session["LoggedUser"]).Id);

                if (accessLevel == AccessLevel.None || accessLevel == AccessLevel.Read)
                {
                    return new HttpUnauthorizedResult();
                }

                TempData["CreatedEvent"] = calendarEvent.Title;
                calendarEvent.ChangeTimesToUTC(((User)Session["LoggedUser"]).TimeZone);
                db.Events.Add(calendarEvent);
                db.SaveChanges();
                return RedirectToAction("Show", "Calendar", new { id = calendarEvent.CalendarId, selectedDate = calendarEvent.StartTime });
            }
            return View(calendarEvent);
        }

        /// <summary>
        /// Deletes selected event from database. Redirects to calendar main page.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(int id)
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login", "User");
            }

            CalendarEntityContainer db = new CalendarEntityContainer();

            Event eventToDelete = db.Events.FirstOrDefault(e => e.Id == id);

            if (eventToDelete == null)
            {
                return new HttpNotFoundResult();
            }

            AccessLevel accessLevel = eventToDelete.Calendar.GetUserAccessLevel(((User)Session["LoggedUser"]).Id);

            if (accessLevel == AccessLevel.None || accessLevel == AccessLevel.Read)
            {
                return new HttpUnauthorizedResult();
            }

            int calendarId = eventToDelete.CalendarId;
            DateTime eventTime = eventToDelete.StartTime;

            TempData["DeletedEvent"] = eventToDelete.Title;
            db.Events.Remove(eventToDelete);
            db.SaveChanges();

            return RedirectToAction("Show", "Calendar",
                new { id = calendarId, selectedDate = eventTime });
        }


        /// <summary>
        /// Shows page where user may edit calendar.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            CalendarEntityContainer db = new CalendarEntityContainer();

            Event calendarEvent = db.Events.FirstOrDefault(e => e.Id == id);

            if (calendarEvent == null)
            {
                return new HttpNotFoundResult();
            }

            AccessLevel accessLevel = calendarEvent.Calendar.GetUserAccessLevel(((User)Session["LoggedUser"]).Id);

            if (accessLevel == AccessLevel.None || accessLevel == AccessLevel.Read)
            {
                return new HttpUnauthorizedResult();
            }

            calendarEvent.ChangeToLocalTime(((User)Session["LoggedUser"]).TimeZone);

            return View(calendarEvent);
        }

        /// <summary>
        /// Updates selected event in database.
        /// </summary>
        /// <param name="calendarEvent"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(Event calendarEvent)
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login", "User");
            }


            if (calendarEvent.AllDay)
            {
                calendarEvent.EndTime = calendarEvent.StartTime;
            }

            if (calendarEvent.StartTime > calendarEvent.EndTime)
            {
                ModelState.AddModelError("", "Event end time cannot be before event start time.");
            }

            if (ModelState.IsValid)
            {
                CalendarEntityContainer db = new CalendarEntityContainer();

                Models.Calendar calendar = db.Calendars.FirstOrDefault(c => c.Id == calendarEvent.CalendarId);

                if (calendar == null)
                {
                    return new HttpNotFoundResult();
                }

                AccessLevel accessLevel = calendar.GetUserAccessLevel(((User)Session["LoggedUser"]).Id);

                if (accessLevel == AccessLevel.None || accessLevel == AccessLevel.Read)
                {
                    return new HttpUnauthorizedResult();
                }

                calendarEvent.ChangeTimesToUTC(((User)Session["LoggedUser"]).TimeZone);
                db.Entry(calendarEvent).State = EntityState.Modified;
                db.SaveChanges();
                TempData["ModifiedEvent"] = calendarEvent.Title;
                return RedirectToAction("Show", "Calendar", new { id = calendarEvent.CalendarId, selectedDate = calendarEvent.StartTime });
            }
            return View(calendarEvent);
        }
    }
}

Calendar/Views/Event/Create.cshtml
@model Calendar.Models.Event
@{
    ViewBag.Title = "Create event";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#AllDay').change(function () {
            if ($(this).is(":checked")) {
                $('#EndTime').val($('#StartTime').val());
                $('#EndTime').prop('disabled', true);
            } else {
                $('#EndTime').prop('disabled', false);
            }
        });
    });
</script>

@using (Html.BeginForm("Create", "Event", null, FormMethod.Post, new { style = "max-width:330px;margin:0 auto" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <h2>Create event</h2>
    @Html.HiddenFor(model => model.CalendarId)
    <div>
        @Html.TextBoxFor(model => model.Title, new { @class = "form-control", placeholder = "Title" })
        @Html.ValidationMessageFor(model => model.Title)
    </div>
    <div>
        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", placeholder = "Description" })
        @Html.ValidationMessageFor(model => model.Description)
    </div>
    
    <div>
        @Html.Label("Choose event start time:")
        <input class="form-control" type="datetime-local" data-val="true" data-val-date="The field StartTime must be a date." data-val-required="Field StartTime is required." id="StartTime" name="StartTime"  value="@Model.StartTime.ToString("yyyy-MM-ddTHH:mm")" min="1999-01-01T00:00"/>
        @Html.ValidationMessageFor(model => model.StartTime)
    </div>
    <div>
        @if (Model.AllDay)
        {
        @Html.Label("Choose event end time:")
            <input class="form-control" type="datetime-local" data-val="true" data-val-date="The field EndTime must be a date." data-val-required="Pole EndTime jest wymagane." id="EndTime" name="EndTime"  value="@Model.EndTime.ToString("yyyy-MM-ddTHH:mm")" min="1999-01-01T00:00" disabled="disabled"/>
            
        }
        else
        {
        @Html.Label("Choose event end time:")
            <input class="form-control" type="datetime-local" data-val="true" data-val-date="The field EndTime must be a date." data-val-required="Pole EndTime jest wymagane." id="EndTime" name="EndTime"  value="@Model.EndTime.ToString("yyyy-MM-ddTHH:mm")" min="1999-01-01T00:00"/>
  
        }
        @Html.ValidationMessageFor(model => model.EndTime)
    </div>
    <div>
        <label>
            @Html.CheckBoxFor(model => model.AllDay)
            All day event
        </label>
        @Html.ValidationMessageFor(model => model.AllDay)
    </div>
    <p>
        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Submit" />
    </p>
}

Calendar/Views/Event/Details.cshtml
@using Calendar.Models
@model global::Calendar.ViewModels.EventDetailsViewModel
@{
    ViewBag.Title = "Event details";
}

@if (Model == null)
{
    <div class="alert alert-danger" role="alert">Error! Event not found</div>
}
else
{
    <h2>Event details</h2>
    <p style="word-wrap: break-word">Title: @Model.Event.Title</p>
    <p style="word-wrap: break-word">Description: @Model.Event.Description</p>
    <p>Event start: @Model.Event.StartTime.ToString("yyyy-MM-dd HH:mm")</p>
    if (Model.Event.AllDay)
    {
    <p>Event end: All day event</p>
    }
    else
    {
    <p>Event end: @Model.Event.EndTime.ToString("yyyy-MM-dd HH:mm")</p>
    }

    if (Model.AccessLevel == AccessLevel.Owner || Model.AccessLevel == AccessLevel.Write)
    {
    @Html.ActionLink("Edit", "Edit", new { id = Model.Event.Id }, new { @class = "btn btn-primary", type = "button", style = "width: 100px; margin-right: 10px; float: left" })
        using (Html.BeginForm("Delete", "Event", null, FormMethod.Post))
        {
    @Html.AntiForgeryToken()
            <p>
                <input hidden="hidden" name="id" value="@Model.Event.Id"/>
                <input class="btn btn-danger" type="submit" value="Delete" style="width: 100px; float: left" />
            </p>
        }
    }

}

Calendar/Views/Event/Edit.cshtml
@model Calendar.Models.Event
@{
    ViewBag.Title = "Edit event";
}


<script type="text/javascript">
    $(document).ready(function () {
        $('#AllDay').change(function () {
            if ($(this).is(":checked")) {
                $('#EndTime').val($('#StartTime').val());
                $('#EndTime').prop('disabled', true);
            } else {
                $('#EndTime').prop('disabled', false);
            }
        });
    });
</script>

@if (Model == null)
{
    <div class="alert alert-danger" role="alert">Error! Event not found</div>
}
else
{
    using (Html.BeginForm("Edit", "Event", null, FormMethod.Post, new { style = "max-width:330px;margin:0 auto" }))
    {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <h2>Create event</h2>
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.CalendarId)
    <div>
        @Html.TextBoxFor(model => model.Title, new { @class = "form-control", placeholder = "Title" })
        @Html.ValidationMessageFor(model => model.Title)
    </div>
    <div>
        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", placeholder = "Description" })
        @Html.ValidationMessageFor(model => model.Description)
    </div>

    <div>
        @Html.Label("Choose event start time:")
        <input class="form-control" type="datetime-local" data-val="true" data-val-date="The field StartTime must be a date." data-val-required="Field StartTime is required." id="StartTime" name="StartTime"  value="@Model.StartTime.ToString("yyyy-MM-ddTHH:mm")" min="1999-01-01T00:00"/>
        @Html.ValidationMessageFor(model => model.StartTime)
    </div>
    <div>
        @if (Model.AllDay)
        {
            @Html.Label("Choose event end time:")
            <input class="form-control" type="datetime-local" data-val="true" data-val-date="The field EndTime must be a date." data-val-required="Pole EndTime jest wymagane." id="EndTime" name="EndTime"  value="@Model.EndTime.ToString("yyyy-MM-ddTHH:mm")" min="1999-01-01T00:00" disabled="disabled"/>

        }
        else
        {
            @Html.Label("Choose event end time:")
            <input class="form-control" type="datetime-local" data-val="true" data-val-date="The field EndTime must be a date." data-val-required="Pole EndTime jest wymagane." id="EndTime" name="EndTime"  value="@Model.EndTime.ToString("yyyy-MM-ddTHH:mm")" min="1999-01-01T00:00"/>

        }
        @Html.ValidationMessageFor(model => model.EndTime)
    </div>
    <div>
        <label>
            @Html.CheckBoxFor(model => model.AllDay)
            All day event
        </label>
        @Html.ValidationMessageFor(model => model.Description)
    </div>
    <p>
        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Submit" />
    </p>
    }
}